### ISSUE TITLE
Site does not build with Hugo v0.29 or v0.31

### ISSUE THREAD

**Issue by bramp** [gopheracademy/gopheracademy-web#236]
When I run:
```shell
gopheracademy-web$ hugo server
```

No errors are printed, but going to http://localhost:1313/ shows a blank page, specifically:

```shell
$ curl -v http://127.0.0.1:1313/
...
< HTTP/1.1 200 OK
...
<pre>
</pre>
```

When I run `hugo` it generates a bunch of files in the `public` directory, but no HTML files are generated, just lots of index.xml, for example:

```shell
gopheracademy-web$ tree public/
public/
├── README.md
├── advent-2013
│   └── index.xml
├── advent-2014
│   └── index.xml
├── advent-2015
│   └── index.xml
```

If I run `hugo -v` I see errors like:
```
WARN 2017/11/26 13:32:23 [en] Unable to locate layout for "page": [advent-2017/single.html.html advent-2017/single.html _default/single.html.html _default/single.html theme/advent-2017/single.html.html theme/advent-2017/single.html theme/_default/single.html.html theme/_default/single.html]
```

I was running Hugo 0.29 (installed from homebrew), but I updated to 0.31 (the latest version), yet I have the same issues.  I don't know which version people have been using to build the site, but I know Hugo has made breaking changes in the past which have broken sites.

**Comment by natefinch** [comment]
looks like you need to tell hugo to use config-main.toml
since the layout directory is layouts-main  not just “layouts” (edited)
so, `hugo -config config-main.toml` should work (edited)
the reason no pages are created by default is because it looks for a layouts folder and doesn’t see one, so it doesn’t create anything.

Not sure why this is.... but at the very least the readme should be updated.

**Comment by bketelsen** [comment]
if anyone has time to look at the template breaks in the new versions of Hugo I can upgrade the server when we get a fix merged.
